### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/intrastat-extrastat#23]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] hs_code_link
- [x] intrastat_base - ~~By @BT-kaberer - #28~~ - By @rvalyi - #37  
- [x] intrastat_product - ~~By @BT-kaberer - #30~~ By @rvalyi - #47 
- [x] product_harmonized_system - ~~By @BT-kaberer - #29~~ - By @rvalyi - #37

**Comment by ghost** [comment]
Hey @pedrobaeza 

I will start migrating 
 intrastat_base
 intrastat_product
 product_harmonized_system
to version 11.0

**Comment by pedrobaeza** [comment]
OK, noted

**Comment by emagdalenaC2i** [comment]
@pedrobaeza intrastat_product - By @BT-kaberer - #30 is closed and superseded by #47

product_harmonized_system - By @BT-kaberer - #29 is closed and superseded by #47 that is already merged

**Comment by luc-demeyer** [comment]
closing since 11.0 migration has been completed a while ago.
